FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

COPY . .

RUN dotnet restore Presentation/ManualDoCoroinha.Web/ManualDoCoroinha.Web.csproj

RUN dotnet publish Presentation/ManualDoCoroinha.Web/ManualDoCoroinha.Web.csproj \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:8.0

WORKDIR /app

COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:10000

EXPOSE 10000

ENTRYPOINT ["dotnet", "ManualDoCoroinha.Web.dll"]